Add rand feature flag to the example documentation
rust-bitcoin/rust-bitcoin pull request #1416
Opened 2022-11-27 18:13 UTC by yancyribbens

It's confusing trying to follow the documentation [here](https://docs.rs/bitcoin/latest/bitcoin/util/address/index.html) unless you know to enable the `rand` feature flag.  This PR updates the docs so people know to enable the flag.

```
22:35 < control> hello, how can i generate a simple wallet address using rust bitcoin? cant find working example
22:45 < andytoshi> control: do you have a private key?
22:45 < andytoshi> what kind of address do you want to generate?
22:46 < andytoshi> my guess would be that you want to use bdk rather than rust-bitcoin directl
22:48 < control> P2PKH address and generate private key. just as simple as bit library in python does
22:52 < control> im trying to run this example
22:52 < control> https://docs.rs/bitcoin/latest/bitcoin/util/address/index.html
22:52 < control> but it says ^^^^ could not find `rand` in `secp256k1`
```

2022-11-27 20:53 UTC, Kixunil approved these changes
ACK 50a665d966f95b310353a91d11da6a7da24261f2

2022-11-27 23:46 UTC, yancyribbens commented on bitcoin/src/address.rs
> +//! bitcoin = { version = "*", features = ["rand"] }
@TheBlueMatt good point - the wild card operator works better here.

2022-11-28 04:00 UTC, tcharding submitted a review, later dismissed
ACK 28fdbbaba8d201bd343c875bff36302d07b164ad

2022-11-28 04:01 UTC, tcharding commented
Thanks for the contribution man! I built the docs and verified that it looks good in HTML.

2022-11-28 09:56 UTC, Kixunil requested changes

2022-11-28 09:56 UTC, Kixunil commented on bitcoin/src/address.rs
> +//! bitcoin = { version = "*", features = ["rand"] }
Please, don't use wildcard here - it'd tempt people into using it in real code which is a bad idea. I suggest using `...`.
Also it's not `rust` but `toml`.

2022-11-28 16:32 UTC, apoelstra approved these changes
ACK f7a6d171438bd97b371efcc9adb01d24b0f345cd

2022-11-28 19:18 UTC, Kixunil approved these changes
ACK f7a6d171438bd97b371efcc9adb01d24b0f345cd

2022-11-29 14:22 UTC, merged