[WIP] 1514: fix formatting in opcodes
rust-bitcoin/rust-bitcoin pull request #1528
Opened 2023-01-04 07:04 UTC by td-bn

See  #1514.

2023-01-04 10:41 UTC, Kixunil approved these changes
ACK dfc670a792469ba31bfd40329556f80359cea46a

Nice, thanks! Feel free to unify it with the module definition, as we discussed, if you like.

2023-01-04 18:42 UTC, apoelstra approved these changes
ACK e668266e38f9fc9d2fb3e4fbed7c234bfb9660c4

2023-01-04 22:16 UTC, Kixunil requested changes
Apart from broken docs, this looks fine.

2023-01-04 22:16 UTC, Kixunil commented on bitcoin/src/blockdata/opcodes.rs
> +        use self::all::*;
It shouldn't matter whether this is in a macro but I don't care.

2023-01-04 22:16 UTC, Kixunil commented on bitcoin/src/blockdata/opcodes.rs
> +                $(
Nit: space at the end of this line.

2023-01-04 22:16 UTC, Kixunil commented on bitcoin/src/blockdata/opcodes.rs
> +    OP_PUSHBYTES_3 => 0x03, "Push the next 2 bytes as an array onto the stack.";
Unrelated but Satoshi must have had some strong drugs when he decided this.

2023-01-04 22:16 UTC, Kixunil commented on bitcoin/src/blockdata/opcodes.rs
> +                    /// $doc
Unfortunately, this doesn't work. If I'm not mistaken `#[doc = $doc]` should work instead.

2023-01-05 08:41 UTC, Kixunil submitted a review, later dismissed
ACK ed0a055de223b763a42aaf35091b84d67f63ac75

Squashing may be a good idea though.

2023-01-05 12:47 UTC, Kixunil approved these changes
ACK 77799bf5cb43df5c30218c4889674aa17c798233

2023-01-06 13:53 UTC, merged