bip158: Replace usage of HashSet with BTreeSet
rust-bitcoin/rust-bitcoin pull request #1576
Opened 2023-01-22 06:34 UTC by tcharding

The `bip158` module uses a `HashSet` and in order to do so requires the `hashbrown` dependency for "no-std" builds.

We can replace the usage of `HashSet` with a `BTreeSet` in `bip158` and remove the `hashbrown` dependency entirely.

This patch makes no claims about performance cost or benefit of this change. The patch also makes no claims about the validity of the current `HashSet` usage.

The `hashbrown` dependency and `HashSet` usage can be trivially added back in if someone comes up with perf data to back it up.

2023-01-22 14:30 UTC, Kixunil requested changes
Also remove it from `Cargo.toml` :)

2023-01-22 14:31 UTC, Kixunil commented
And yes, I like removing it without claiming anything about perf and re-adding if perf is affected and we can't resolve it without adding the dep.

2023-01-22 21:38 UTC, tcharding commented
> Also remove it from Cargo.toml :)

Face palm, done.

2023-01-23 13:19 UTC, apoelstra approved these changes
ACK 6e56feed57a7c1dda34a8921e796f54b119f4737

2023-01-23 13:38 UTC, merged