Print tool versions in ci
rust-bitcoin/rust-bitcoin pull request #1684
Opened 2023-03-02 05:50 UTC by PaarthAgarwal

Add commands to (verbosely) print out versions of Rust, Clippy, Cargo before each run in CI. Fixes #1124.

2023-03-02 12:47 UTC, Kixunil requested changes
Looks buggy

2023-03-02 12:47 UTC, Kixunil commented on contrib/test.sh
> +if $NIGHTLY; then
This variable is uninitialized.

2023-03-02 12:47 UTC, Kixunil commented on contrib/test.sh
> +fi
Why is this here twice?

2023-03-02 12:47 UTC, Kixunil commented on contrib/test.sh
> +if cargo +nightly --version >/dev/null 2>&1; then
In both cases the output is discarded, so nothing gets printed.

2023-03-05 06:35 UTC, PaarthAgarwal commented
> Looks buggy

Pushed a fix

2023-03-05 13:59 UTC, apoelstra commented
@PaarthAgarwal I appreciate you taking this on, but we need you to test this locally (and to figure out how to do so). It's not an efficient use of reviewer time to iterate on shell scripts like this. Your fixed version is still incorrect. If you are not familiar with shell, or with the meaning of various cargo options, this issue might not be a good first choice.

2023-05-04 06:05 UTC, closed without merging