Avoid usage of atomic types when the 'std' feature is not enabled
rust-bitcoin/rust-bitcoin pull request #1705
Opened 2023-03-09 17:08 UTC by bigspider

Hi! I'm still a beginner with both Rust and cross-compilation, so please take the rest with a few grains of salt!

I'm setting up a project targeting `riscv32i-unknown-none-elf`, which seems not to support atomic types. Even with `--no-default-features` and `no-std`, I would get this error:

```
error[E0432]: unresolved import `alloc::sync`
  --> rust-bitcoin/bitcoin/src/blockdata/script/mod.rs:52:12
   |
52 | use alloc::sync::Arc;
   |            ^^^^ could not find `sync` in `alloc`

error[E0432]: unresolved import `alloc::sync`
   --> rust-bitcoin/bitcoin/src/lib.rs:163:114
    |
163 |     pub use alloc::{string::{String, ToString}, vec::Vec, boxed::Box, borrow::{Borrow, Cow, ToOwned}, slice, rc, sync};
    |                                                                                                                  ^^^^ no `sync` in the root
    |
    = help: consider importing one of these items instead:
            bitcoin_hashes::_export::_core::sync
            core::sync
```

This PR gates the usage of `Arc` so that it's only enabled with the `std` feature.

2023-03-10 09:51 UTC, Kixunil requested changes
Concept ACK, just needs proper gates and doc.

2023-03-10 09:51 UTC, Kixunil commented on bitcoin/src/consensus/encode.rs
> +#[cfg(feature = "std")]
This is imprecise, there are `alloc` targets that don't need `std` for atomics.

[`#[cfg(target_has_atomic = "ptr")]` needs to be used instead](https://doc.rust-lang.org/stable/alloc/sync/index.html)

Also needs `docsrs` gate to document it - see our other gates.

2023-03-10 09:51 UTC, Kixunil commented on bitcoin/src/blockdata/script/mod.rs
>  impl<'a> From<&'a Script> for Arc<Script> {
Apart from different cfg, this needs docsrs too.

2023-03-10 09:53 UTC, Kixunil commented
Also thanks for trying out the unreleased version of our crate and catching this! :)

2023-03-10 10:46 UTC, bigspider commented
Thanks both for the quick review!

Hopefully the gating and docsrs are correct, now.

2023-03-10 10:53 UTC, Kixunil approved these changes
ACK 73fdef04ae68972e3900b5103bd0a1f0b4a12a4e

2023-03-10 11:03 UTC, Kixunil commented
Crap, this is only [available since Rust 1.60](https://github.com/rust-lang/rust/blob/master/RELEASES.md#version-1600-2022-04-07).

Would it be OK to drop non-atomic support for Rust <1.60? That seems the best way to do it. Add 1.60 to `build.rs` and then use this gate:

`#cfg(any(not(rust_v_1_60), target_has_atomic = "ptr"))`

I would keep the docsrs as-is (without Rust version) because it can't render it. Just add doc comment:

> `/// Note: This will fail to compile on old Rust for targets that don't support atomics`

2023-03-10 11:05 UTC, Kixunil commented
Also needs a similar gate in `bitcoin/src/consensus/encode.rs:725`

2023-03-10 12:39 UTC, bigspider commented
No problem on my side to limit non-atomic support to recent versions − it's for a new project where I don't have any version constraints.

Added the additional version gating in df58661307801410d2e06b4f58d49acb008605d4; now praying for the next round of CI :D

2023-03-10 16:18 UTC, apoelstra commented
Looks good to me, though it looks like there's still a missing gate or something according to CI.

Agree with Matt that this is pretty frustrating ... but fortunately for this library we don't directly depend on the functionality.

2023-03-10 16:59 UTC, bigspider commented
I'll try to debug the CI next week (or feel free to take over the PR if you know how to fix it).

Apparently there are also some polyfills if lack of atomics is problematic:  https://github.com/embassy-rs/atomic-polyfill + https://github.com/rust-embedded/critical-section#usage-in-libraries; although I don't see the `riscv32i` target there, only `riscv32imc` − so maybe it still wouldn't solve it for me.

2023-03-10 17:59 UTC, Kixunil commented
@bigspider that polyfill doesn't provide `Arc` anyway. I wouldn't worry about it until someone actually requests it. (But really anyone can create their `Arc<Script>`

2023-03-13 16:30 UTC, bigspider commented
Rebased, hopefully #1708 also fixes the issue I had in the CI.

2023-03-15 16:36 UTC, bigspider commented
Failing CIs seem to be related to the `no-std` feature, and my best guess is that it's because of the incompatible gating between the `std` vs `no-std` used in [bitcoin/src/lib.rs](https://github.com/rust-bitcoin/rust-bitcoin/pull/1705/commits/a6eaed245fc4f27d77c5f63db83c4d7c11fe576a#diff-4dfdb23cc7ad32296bb192c7522a3fbe1b693d09947848e331c8b17c6e4d115d) (where I removed `sync` in `no-std`).

Attempting to fix it with f745630, although the gating gets even uglier there.

2023-03-15 20:58 UTC, bigspider commented
Alright, moved to draft until I figure out how to debug it locally without playing the CI lottery.
Thanks for the patience.

2023-03-16 01:11 UTC, apoelstra commented
You're welcome to play the CI lottery @bigspider. (Probably you don't want to, but don't avoid it because you're worried about bugging us :))

2023-03-16 09:26 UTC, bigspider commented
The last commit was just botched, hopefully 69136b6 does the trick.

It would be great to be able to define a simple gate as an alias for `any(not(rust_v_1_60), target_has_atomic = "ptr")`, but it appears that there's no clean way to detect the presence of atomics in `build.rs`, as people [end up hardcoding the architectures](https://github.com/ferrilab/radium/blob/main/build.rs) for this purpose.

2023-03-16 10:24 UTC, bigspider commented
Rebased on latest master branch.

2023-03-16 11:39 UTC, Kixunil commented
The nightly build failure is unrelated: https://github.com/rust-lang/rust/issues/109209

2023-03-16 18:26 UTC, Kixunil reviewed
Looks good, you just need to squash the commits (we require all commits to pass all tests).

2023-03-16 21:44 UTC, bigspider commented
Done!

2023-03-16 23:21 UTC, apoelstra approved these changes
ACK 2961c0c589b3a49145c98af71190d8572fe11697

2023-03-17 04:27 UTC, Kixunil approved these changes
ACK 2961c0c589b3a49145c98af71190d8572fe11697

2023-03-17 14:14 UTC, merged