Create `ecdsa::LegacySignature` and `ecdsa::SegwitV0Signature`
rust-bitcoin/rust-bitcoin pull request #1989
Opened 2023-08-11 03:49 UTC by tcharding

Not for consideration until after release of v0.31.0

This is a re-spin of #1606 since the sighash types were split already since then.

In an effort to further spit up the ECDSA type into legacy and segwit v0 add two new sig types. Currently unused, as it is this does not buy us much but if we would like to re-design our keys with legacy/segwit in mind then this will be needed.

- Patch 1-5: Only code moves, creating new submodules and moving code, can all be ignored for now. 
- Patch 6 and 7: Do trivial docs fixes. 
- Patch 8: Adds the two new types.

2023-08-14 04:39 UTC, tcharding commented
Note that this PR just duplicates the `ecda::Signature` API and make the inner signatures `pub(crate)` - do we want the `pub`?

2023-09-25 23:10 UTC, tcharding commented
Not sure now if this is going in the right direction.

2023-09-26 12:54 UTC, apoelstra commented
I think this is going in the right direction. The main difficulty as always is that PSBT (the protocol) commingles these types so we'll need a PSBT-specific enum.

Eventually the legacy signature will use legacy keys and segwit signatures will use (compressed only) secp keys, which should also simplify our public key story.

2023-09-26 13:03 UTC, apoelstra commented
One observation I have is that these signature types seem to line up with the scriptpubkey/witness/txout-type table that you mentiend in https://github.com/rust-bitcoin/rust-bitcoin/pull/2084

I wonder if we want to try to create some "output type" trait which uses associated types and constants to capture the workflow here. And we could maybe allow upcasting/downcasting to a "generic" version of the output type and its associated types, for applications like PSBT where things are just byte-serialized.

2023-09-26 20:05 UTC, tcharding commented
Man, I like that idea.

2023-10-10 21:37 UTC, tcharding commented
On ice until next release.

2023-10-31 00:51 UTC, tcharding commented
> I wonder if we want to try to create some "output type" trait which uses associated types and constants to capture the workflow here.

Started in #2154

2024-06-01 21:16 UTC, tcharding commented
Mad, github is not Linux, I can un-delete things :)

2024-06-19 21:53 UTC, tcharding commented
Yes, correct. I just haven't gotten back to this. I'll update the PR description.

2024-06-24 05:53 UTC, Kixunil requested changes
Aside from the changes being weird (rebase issue I guess), I don't think having another signature type without the flags meaningfully improves anything.

2024-06-24 05:53 UTC, Kixunil commented on bitcoin/src/crypto/ecdsa/mod.rs
> -    }
Why was this test deleted?

2024-06-24 05:53 UTC, Kixunil commented on bitcoin/src/crypto/sighash/error.rs
> +}
This is supposed to be a code move but I don't see this enum removed.

2024-06-24 05:53 UTC, Kixunil commented on bitcoin/src/crypto/sighash/sighash_type.rs
> +}
This empty impl looks sus.

2024-06-24 05:53 UTC, Kixunil commented on bitcoin/src/crypto/ecdsa/legacy.rs
> +pub struct Signature(pub(crate) ecdsa::Signature);
I think you've misunderstood the point of the suggested changes. It definitely should carry the sighash flags so they can be put into witness stack correctly. You obtain the signature by signing a sighash which also carries the flags.

2024-06-24 07:07 UTC, tcharding commented
I don't care enough about this to push it forward, I have many other things I can do if there is push back.

2024-06-24 07:07 UTC, closed without merging