WIP: Add ops to absolute::Height
rust-bitcoin/rust-bitcoin pull request #2181
Opened 2023-11-07 23:33 UTC by tcharding

Draft for comments and while flesh this out. This PR is primarily to support #2090 (and #2180). It will likely need to be released as point releases to `0.30` and `0.31` so what ever we add here should be polished.

Currently it just does the minimum required to support the get next target stuff.

2023-11-09 12:51 UTC, yancyribbens commented
I added a comment to https://github.com/rust-bitcoin/rust-bitcoin/issues/1639 that I think relates to this PR.

2023-11-10 14:02 UTC, apoelstra commented
I think it makes sense to add two heights. In fact I think it makes more sense than it does to add integers.

2023-11-12 21:49 UTC, tcharding commented
Consider this train of thought.:

1. What is the block height of the next block - its `inc(block_height)`
2. What is `inc(block_height)` - its `block_height + 1`
3. What is `1`, its an integer not a height, what about 6 blocks in the future, again seems like 6 is an integer

At one stage I implemented both `ops::Add<Height>` and `ops::Add<u32>` but I remove the default RHS (Height + Height) one. Do you think we should have both? Or do you still think we should not have Height + int at all still?

2023-11-13 18:28 UTC, apoelstra commented
I disagree with point 3.

For convenience's sake I think we should have both, but conceptually `blockheight + 1` is adding one block to a count of blocks. It's not adding some sort of platonic integer.

2023-11-13 19:53 UTC, tcharding commented
No sweat, I'll add both in.

2023-11-14 13:17 UTC, Kixunil commented
I think this is very similar to `Instant` vs `Duration` in `std. As such I don't think it makes sense to add two absolute lock times but it does make sense to add relative locktime to absolute or add two relative lock times together.

2023-11-14 21:41 UTC, tcharding commented
Good points, I'll re-spin. Thanks

2023-11-14 22:50 UTC, tcharding commented
Won't get green CI until rebased on top of #2188

2023-11-16 13:31 UTC, apoelstra commented
There's no need to actually use the std `saturating_div` if it's identical to `/`. So you can get MSRV to pass by just using /.

2023-11-16 19:42 UTC, tcharding commented
hah, good point. Used `/` in absolute and relative, `checked_sub` and `saturating_sub` - along with a comment.

2023-11-17 18:26 UTC, Kixunil requested changes
NACK, this has several problems.

2023-11-17 18:26 UTC, Kixunil commented on bitcoin/src/blockdata/locktime/absolute.rs
> +    pub const fn decrement(self) -> Height { self.saturating_sub(1) }
These seem arbitrary. There's a reason Rust doesn't have the `++` operator. I suggest having a method called `offset` that just accepts an int.

2023-11-17 18:26 UTC, Kixunil commented on bitcoin/src/blockdata/locktime/absolute.rs
> +    pub const fn checked_add(self, rhs: u32) -> Option<Self> {
This is not the same type which is unusual and possibly a foot gun but I understand something like that could be handy. I would call it `offset` to distinguish it from the usual operations.

2023-11-17 18:26 UTC, Kixunil commented on bitcoin/src/blockdata/locktime/absolute.rs
> +    pub const fn checked_sub(self, rhs: u32) -> Option<Height> {
`neg_offset` or other name?

2023-11-17 18:26 UTC, Kixunil commented on bitcoin/src/blockdata/locktime/absolute.rs
> +impl ops::Add<u32> for Height {
This absolutely goes against the idea of having strong newtypes. I really, really, really don't like this.

2023-11-17 18:26 UTC, Kixunil commented on bitcoin/src/blockdata/locktime/absolute.rs
> +impl ops::Mul<relative::Height> for Height {
This is definitely wrong. What does multiplying an instant with duration even mean? Or blocks squared? Even if we wanted it it'd need `HeightSquared` output type.

2023-11-17 18:26 UTC, Kixunil commented on bitcoin/src/blockdata/locktime/absolute.rs
> +impl ops::Mul<u32> for Height {
Note that while I was in favor of this in other places I don't think it's appropriate here. Multiplying by a scalar is scaling but multiplying an instant doesn't seem to make sense. Think of height like specific date and time. What does `(January 3rd 2009) * 42` mean?

2023-11-17 18:26 UTC, Kixunil commented on bitcoin/src/blockdata/locktime/absolute.rs
> +impl ops::Div<relative::Height> for Height {
This is also nonsensical.

2023-11-17 18:26 UTC, Kixunil commented on bitcoin/src/blockdata/locktime/absolute.rs
> +impl ops::Div<Height> for u32 {
Also this is nonsensical.

2023-11-17 18:26 UTC, Kixunil commented on bitcoin/src/blockdata/locktime/absolute.rs
> +}
Bunch of other dubious operations like above.

2023-11-17 18:26 UTC, Kixunil commented on bitcoin/src/blockdata/locktime/relative.rs
> +    pub const fn decrement(self) -> Height { self.saturating_sub(1) }
As above, I don't think this is useful.

2023-11-17 18:26 UTC, Kixunil commented on bitcoin/src/blockdata/locktime/relative.rs
> +    }
RHS should be `Self` here and in several other methods below.

2023-11-17 18:26 UTC, Kixunil commented on bitcoin/src/blockdata/locktime/relative.rs
> +    pub const fn checked_mul(self, rhs: u16) -> Option<Self> {
Notably, this one is scaling and **does** actually make sense. Also other muls and divs below.

2023-11-17 18:26 UTC, Kixunil commented on bitcoin/src/blockdata/locktime/relative.rs
> +}
Again not type safe

2023-11-17 18:26 UTC, Kixunil commented on bitcoin/src/blockdata/locktime/relative.rs
> +    type Output = Height;
This shouldn't exists because there's no `HeaightSquared` (Or `BlockchainArea`?)

2023-11-17 18:26 UTC, Kixunil commented on bitcoin/src/blockdata/locktime/relative.rs
> +    type Output = Height;
This **could** actually exist returning a unitless ratio - the tye should then be `u16` though, not `Height`.

2023-11-17 18:26 UTC, Kixunil commented on bitcoin/src/blockdata/locktime/relative.rs
> +}
OK.

2023-11-17 18:26 UTC, Kixunil commented on bitcoin/src/blockdata/locktime/relative.rs
> +    type Output = Height;
Unitless.

2023-11-17 18:26 UTC, Kixunil commented on bitcoin/src/blockdata/locktime/relative.rs
> +}
`*Assign`s need to be according to the above.

2023-11-17 19:26 UTC, tcharding commented
hmm, thanks for the review man. These ops PRs are thorny. I'll come back to this.

2024-05-22 23:20 UTC, closed without merging