feat: remove zeroed vector by pushing front
rust-bitcoin/rust-bitcoin pull request #3227
Opened 2024-08-23 14:53 UTC by ChrisCho-H

Remove useless zeroed vector following https://github.com/rust-bitcoin/rust-bitcoin/issues/3131.
1. Init vector with capacity not to realloc when pushing.
2. If vector is empty(the first iteration), push data from front.
3. Iterate vector from the front, and copy it from the end.

2024-08-23 16:22 UTC, jamillambert reviewed
The CI fail is because the `vec!` macro is now only used in the `#[test]` module and the unused lint does not look in test.  If you change line 21 from `#[macro_use]` to `#[cfg_attr(test, macro_use)]` it should fix the issue.

2024-08-23 17:14 UTC, Kixunil commented
Nice!

@jamillambert I think `use alloc::vec;` in `tests` module should work too and I'd find it nicer. But it's fine to use attribute too.

2024-08-23 22:01 UTC, tcharding commented
@jamillambert debugging PRs like a boss, way to go bro, this is super useful.

2024-08-26 12:10 UTC, ChrisCho-H commented
Thanks for the reviews! I've added `use alloc::vec;` in `tests` module.

2024-08-26 15:28 UTC, apoelstra approved these changes
ACK 441aac0a087254fdd56fc744b937f9d16d59583f successfully ran local tests

2024-08-26 16:20 UTC, jamillambert approved these changes
ACK 441aac0a087254fdd56fc744b937f9d16d59583f

2024-08-26 18:36 UTC, Kixunil requested changes
Needs squashing. I have no idea how @apoelstra got to run his per-commit tests without catching this.

2024-08-26 18:41 UTC, apoelstra commented
Which commit and cargo command fails? I can run `cargo test`, `cargo test --all-features --all-targets`, and `cargo test --no-default-features --all-targets` on each commit. (Using `git rebase -x master` which isn't quite correct, but that's my habitual "check each commit manually" command.)

My local tests do a more extensive feature matrix (IIRC it tries each individual feature by itself, and also two random subsets of features, where "random" is seeded by the commit ID or something) but it may have missed something.

2024-08-26 19:01 UTC, apoelstra commented
> If you used `-D warnings` it'd fail but that is maybe too strict for you.

I've had it on in the past but I've always felt bad nitting new contributors because individual commits don't pass a super strict level of scrutiny, which wouldn't be needed just for bisection to work.. For a similar reason I only run clippy on the final commit of PRs.

It also worses the "sometimes you need to squash unrelated stuff together to make the compiler happy" problem that we sometimes encounter in Rust (and which we did encounter in the final commit of this PR.)

So my ACK stands.

2024-08-26 19:04 UTC, Kixunil commented
Yeah, I thought so. Might be worth to run only some very limited categories of `clippy` on every commit (basically those that detect a problem with pretty much 100% certainty).

2024-08-26 19:08 UTC, Kixunil approved these changes
ACK 441aac0a087254fdd56fc744b937f9d16d59583f

2024-08-26 21:53 UTC, merged