BIP 32/SLIP 132 y,z...pub/priv types with generics
rust-bitcoin/rust-bitcoin pull request #469
Opened 2020-09-09 22:10 UTC by dr-orlovsky

An alternative to https://github.com/rust-bitcoin/rust-bitcoin/pull/279 ypub and other extended pub/priv key support with generics. Will add more tests once this will get concept Acks

2020-09-14 18:46 UTC, ulrichard commented
I came here, because the released version of this lib could not decode a ypub from an electrum wallet.
While the version of this PR sucessfully decodes the ypub, deriving any path with something hardened leads to CannotDeriveFromHardenedKey.
Sorry if this is not related to this PR.

2020-09-14 19:49 UTC, sgeisler commented
> deriving any path with something hardened leads to CannotDeriveFromHardenedKey

Well, that's kind of the point of hardened derivation paths, you can only derive them using an xpriv. So you'd need to use an `ExtendedPrivKey` for that (or do the hardened derivation outside of rust-bitcoin).

2020-10-10 16:49 UTC, stevenroose commented
This might be a bit overkill to the solution, but it actually seems quite good. Could you perhaps rebase?

2020-10-11 02:35 UTC, dr-orlovsky commented
@stevenroose rebased and isolated from other PRs

2020-10-16 17:37 UTC, dr-orlovsky commented
@apoelstra can you add "API Break" label to this pls?

2020-10-25 18:50 UTC, stevenroose commented on src/util/bip32.rs
> +pub struct ExtendedPubKey<R: VersionResolver> {
I'm not a fan of the fact that this type becomes generic. I think it must be possible to have this functionality without this type being generic.

2020-12-21 21:58 UTC, dr-orlovsky commented
Agree with @apoelstra in https://github.com/rust-bitcoin/rust-bitcoin/pull/279#issuecomment-732411145 that SLIP's should not be a part of rust-bitcoin

2021-01-14 15:00 UTC, dr-orlovsky commented
Re-opening the PR for another consideration round since zpub/ypubs are important part of existing Bitcoin ecosystem (for instance Electrum always provide them for SegWit enabled wallets, and there is no trivial way of converting them into xpub)

2021-01-14 15:12 UTC, sgeisler commented
Since this kind of is an unofficial standard and has annoyed me a few times already I'd be fine with having a module to parse these into our current xpubs/xprivs and some additional key usage enum. But I would not like to make it a part of our types, I don't want to _have_ to support that standard, I'd often rather throw away the extra parsed info, e.g. when exporting xpubs from electrum to use with miniscript. "I know what I'm doing, don't bother me with different usage encodings!" :laughing: In that sense such a lenient parser would be useful.

If @apoelstra doesn't like it in rust-bitcoin I'd recommend making it a separate crate. That should be easy for a version that doesn't change the xpub type.

2021-01-14 15:19 UTC, dr-orlovsky commented
@sgeisler just in case it's already in https://github.com/LNP-BP/rust-lnpbp/ (specifically in https://github.com/LNP-BP/rust-lnpbp/blob/master/src/bp/slip32.rs). If you use `lnpbp` crate w/o feature flags you will get only `bp` module with such things linked.

2021-01-15 21:01 UTC, apoelstra commented
concept NACK. 

I could be sold on making this more generic for the sake of letting people externally add decoding code for ypubs, zpubs, if it weren't too big a diff. But this code is pretty-much a perfect example of why these standards are terrible and not something we want in the library. Hundreds of lines of special-purpose code that do a tiny fraction of what descriptors do, and which require constant updating for every new output type.

2021-01-15 21:02 UTC, apoelstra requested changes
f

2021-01-16 17:12 UTC, dr-orlovsky commented
@apoelstra seems like your review comment was cut to a single letter `f`. Nevertheless, I can assume what you was going to say :)

Ok, so the problem is how to deal with y/zpubs exported from Electrum: many pieces of software has to do this while using rust-bitcoin.

2021-01-16 18:04 UTC, shesek commented
I ended up writing a [`XyzPubKey`](https://github.com/bwt-dev/bwt/blob/master/src/util/xpub.rs) wrapper that deals with deserialization from SLIP32 and conversion into descriptors. I didn't find doing this outside of rust-bitcoin too terrible, but can definitely see the value in having a more accessible way to do it. Maybe as an external crate though?

2021-01-16 18:06 UTC, apoelstra commented
I think it makes sense as an external crate which just converts them to descriptors.

2021-01-16 18:07 UTC, apoelstra commented
BTW - github does not let you NACK things, only "request changes", and it does not let you do so without a non-zero-length message. Hence my "f" comment.

2021-01-16 20:28 UTC, closed without merging

2021-01-19 15:20 UTC, dr-orlovsky commented
Slip132 is done as a separate crate: https://crates.io/crates/slip132

2021-02-11 22:19 UTC, dr-orlovsky commented
@apoelstra sorry with brining this topic again, but I have occasionally found that ypub/zpubs are defined in BIP-49 and BIP-84, so this is not some "custom" SLIP-132 and the final bitcoin specs - widely used in the industry (for instance you can't export Electrum SegWit keys w/o supporting these standards).

2021-02-12 01:09 UTC, apoelstra commented
Lots of things have BIP numbers, and lots of things are done by Electrum. This doesn't make them a good idea and doesn't make them a good fit for rust-bitcoin.

I think descriptors are strictly better than ypubs and zpubs and descriptors are still not a part of rust-bitcoin.