bump version to 0.25.1
rust-bitcoin/rust-bitcoin pull request #491
Opened 2020-10-07 22:03 UTC by apoelstra

2020-10-07 22:23 UTC, apoelstra commented
need to add https://github.com/rust-bitcoin/rust-bitcoin/pull/480 to changelog

2020-10-09 13:52 UTC, dr-orlovsky commented
https://github.com/rust-bitcoin/rust-bitcoin/commit/3618d7a41d8aadd1f3c1762969893012cefff899 was a breaking change, so it can't be 0.25.1 anymore. See https://github.com/rust-bitcoin/rust-miniscript/pull/153

2020-10-09 13:53 UTC, dr-orlovsky requested changes
NACK: https://github.com/rust-bitcoin/rust-bitcoin/commit/3618d7a41d8aadd1f3c1762969893012cefff899 was a breaking change, so it can't be 0.25.1 anymore. See https://github.com/rust-bitcoin/rust-miniscript/pull/153

2020-10-09 14:18 UTC, stevenroose commented
> NACK: [3618d7a](https://github.com/rust-bitcoin/rust-bitcoin/commit/3618d7a41d8aadd1f3c1762969893012cefff899) was a breaking change, so it can't be 0.25.1 anymore. See [rust-bitcoin/rust-miniscript#153](https://github.com/rust-bitcoin/rust-miniscript/pull/153)

Hmm that method returns a `Result` while it shouldn't do that. Engines don't error on IO. I'll create a PR to fix that.

2020-10-09 14:22 UTC, stevenroose commented
Here: https://github.com/rust-bitcoin/rust-bitcoin/pull/493

2020-10-09 14:59 UTC, apoelstra commented
Ok #493 is merged

2020-10-12 02:45 UTC, dr-orlovsky commented
Is it possible to release this version on Monday pls? Any more reviewers, @stevenroose, @elichai?

2020-10-14 13:34 UTC, apoelstra commented
@dr-orlovsky I would like to get #413 in first.

2020-10-14 13:47 UTC, apoelstra commented
Should maybe add https://github.com/rust-bitcoin/rust-bitcoin/pull/500 to changelog

2020-10-14 16:30 UTC, apoelstra commented
Should add https://github.com/rust-bitcoin/rust-bitcoin/pull/413 to changelog

2020-10-16 17:20 UTC, dr-orlovsky commented on CHANGELOG.md
> +- Expose [the raw sighash message](https://github.com/rust-bitcoin/rust-bitcoin/pull/485) from sighash computations
```suggestion
- [Add serde implementation for PSBT data structs](https://github.com/rust-bitcoin/rust-bitcoin/pull/497)
- [Add FromStr/Display implementation for SigHashType](https://github.com/rust-bitcoin/rust-bitcoin/pull/497/commits/a4a7035a947998c8d0d69dab206e97253fd8e048)
- Expose [the raw sighash message](https://github.com/rust-bitcoin/rust-bitcoin/pull/485) from sighash computations
```

2020-10-16 23:35 UTC, dr-orlovsky approved these changes

2020-10-19 19:34 UTC, TheBlueMatt approved these changes
I didnt review anything in the bump, but, like, the version number change looks like a version number change.

2020-10-20 09:42 UTC, stevenroose approved these changes

2020-10-20 13:37 UTC, merged