Add Custom Signet support
rust-bitcoin/rust-bitcoin pull request #727
Opened 2021-11-28 15:59 UTC by aitorjs

The PR is to add [Custom Signet](https://en.bitcoin.it/wiki/Signet#Custom_Signet) to the Network enum using the Signet configuration but with a network magic bytes defined by an environment variable of the operative system.

One way to define the environment variable on GNU/Linux:
```
echo "export SIGNET_MAGIC=\"SIGNET_MAGIC\" ">> $HOME/.bashrc
source $HOME/.bashrc
```

2021-11-29 01:05 UTC, tcharding reviewed
Thanks for your contribution! What benefit do you think there is to this approach of adding a new `Network::CSignet` variant as opposed to just allowing an env var to set the magic bytes of `Network::Signet`?

I'm purposefully leaving this review very high level. I did play around with your code a bit, if you are interested in the language usage that I changed I pushed a branch to my own tree for you to look at if you so wish (same branch name, `github.com/tcharding/rust-bitcoin`).

2021-11-29 15:39 UTC, aitorjs commented
> What benefit do you think there is to this approach of adding a new Network::CSignet variant as opposed to just allowing an env var to set the magic bytes of Network::Signet?

_Adding a new Network::CSignet variant_, signet and custom signet could be used and another constants for CSignet could be changed in the code, not only the magic bytes.
_Allowing an env var to set the magic bytes of Network::Signet,_  only signet or custom signet could be used and only the magic bytes could be changed in the code .

I thought it would be better to be able to use both networks, instead of not being able to use Signet because I'm using Custom Signet. ¿What  do you think about it?

> I'm purposefully leaving this review very high level. I did play around with your code a bit, if you are interested in the language usage that I changed I pushed a branch to my own tree for you to look at if you so wish (same branch name, github.com/tcharding/rust-bitcoin).

Thanks so much for the improvements! I did another commit in the PR with the improvements and changes on tests.

2021-11-29 21:58 UTC, tcharding commented
Great. You'll likely want to squash this all down into a single commit now so that its easier for others to review. Review time is super valuable at the moment, the easier we make it for reviewers the quicker we can all make progress. There should also not be any merge commits in the PR, rebase and force push this guy please. Good work.

2021-11-29 22:00 UTC, tcharding commented
> I thought it would be better to be able to use both networks, instead of not being able to use Signet because I'm using Custom Signet. ¿What do you think about it?

I'll leave this for others to answer, I personally have never tested against more than a single bitcoin network at a time but just because I do that does not mean its the only way :)

2021-12-02 19:30 UTC, Kixunil requested changes
I'm strongly against pulling the magic from env. It ties what was otherwise a simple value to the specific way of configuring things, even requiring `std`. It also makes testing more annoying - suddenly tests depend on env vars, which is not great.

I suggest to either just return `Option<u32>`, `None` meaning "custom signet" or carry signet information inside `CSignet` variant (presumably requires larger refactor because of `user_enum!` macro). I'm open to other ideas as long as they don't depend on some global state.

2021-12-21 17:13 UTC, apoelstra commented
Agreed, we cannot have functionality-changing behavior in env vars in a library.

2022-10-30 23:35 UTC, tcharding commented
Are you working on this PR till [aitorjs](https://github.com/aitorjs)?

2023-02-20 01:41 UTC, tcharding commented
No movement on this for a few months, closing. Please re-open @aitorjs if this is still being worked on or anyone else if you want to see this functionality get in.

2023-02-20 01:41 UTC, closed without merging