add MAX_MONEY public constant to Amount
rust-bitcoin/rust-bitcoin pull request #742
Opened 2021-12-14 16:55 UTC by z8674558

Closes https://github.com/rust-bitcoin/rust-bitcoin/issues/740

2021-12-14 22:27 UTC, Kixunil reviewed
Could you add the same constant for unsigned `Amount` too, please?

Note for other reviewers: `Mul::mul` is not `const` so `21_000_000 * Self::ONE_BTC` wouldn't work.

2021-12-15 03:22 UTC, z8674558 commented
@Kixunil thanks, updated.

2021-12-15 08:44 UTC, sanket1729 commented
We should address why @dpc reacted with thumbs down before we proceed on this.

2021-12-15 09:56 UTC, Kixunil requested changes

2021-12-15 09:59 UTC, Kixunil commented
@sanket1729 I think he thought it is an implementation of #620 but it isn't. @dpc could you clarify?

2021-12-15 10:01 UTC, z8674558 commented on src/util/amount.rs
> +    pub const MAX_MONEY: SignedAmount = SignedAmount(21_000_000 * 100_000_000);
🙏

2021-12-15 16:26 UTC, dpc commented
Correct. Please don't mind me.

2021-12-15 17:00 UTC, Kixunil approved these changes
ACK ab12410ae87231d4bb8c0c2886f87cd2a2072aeb

2021-12-16 08:22 UTC, RCasatta approved these changes
ACK ab12410ae87231d4bb8c0c2886f87cd2a2072aeb

2021-12-16 08:28 UTC, merged